
#server:
#  port: 8090
spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  thymeleaf:
    cache: false
server:
  error:
    whitelabel:
      enabled: false

---

spring:
  profiles: dev
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/crossover
    username: root
    password: admin
    driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    cache: false
server:
  error:
    whitelabel:
      enabled: false



#spring.datasource.url=jdbc:mysql://localhost:3306/journals?createDatabaseIfNotExist=true
#spring.datasource.username=root
#spring.datasource.password=admin
#spring.datasource.driver-class-name=com.mysql.jdbc.Driver

#none, validate, update, create, create-drop
#spring.jpa.database-platform=org.hibernate.dialect.MySQL5Dialect

---

spring:
  profiles: test
  datasource:
    #schema: schema.sql
    #data: data.sql
    initialize: false
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
