create table container (
  id bigint generated by default as identity,
  name varchar(255) not null,
  primary key (id)
);
create table feature (
  id bigint generated by default as identity,
  name varchar(255) not null,
  value varchar(255) not null,
  container_id bigint not null,
  primary key (id)
);
create table role (
  id integer generated by default as identity,
  role varchar(255),
  primary key (id)
);
create table user (
  id bigint generated by default as identity,
  active boolean not null,
  password varchar(255) not null,
  username varchar(255) not null,
  primary key (id)
);
create table user_role (
  user_id bigint not null,
  role_id integer not null,
  primary key (user_id, role_id)
);
alter table feature
  add constraint FK9dy79xd6uo0jp6ve7fcf48l0m
foreign key (container_id)
references container;

alter table user_role
  add constraint FKa68196081fvovjhkek5m97n3y
foreign key (role_id)
references role;

alter table user_role
  add constraint FK859n2jvi8ivhui0rl0esws6o
foreign key (user_id)
references user;